LOAD DATA LOCAL INFILE
'/tmp/dataset/football/leagues.csv' INTO TABLE
leagues FIELDS TERMINATED BY ',' LINES TERMINATED BY
'\n' IGNORE 1 ROWS;


LOAD DATA LOCAL INFILE
'/tmp/dataset/football/teams.csv' INTO TABLE
teams FIELDS TERMINATED BY ',' LINES TERMINATED BY
'\n' IGNORE 1 ROWS;


LOAD DATA LOCAL INFILE
'/tmp/dataset/football/players.csv' INTO TABLE
players FIELDS TERMINATED BY ',' LINES TERMINATED BY
'\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE
'/tmp/dataset/football/appearances.csv' INTO TABLE
appearances FIELDS TERMINATED BY ',' LINES TERMINATED BY
'\n' IGNORE 1 ROWS;


LOAD DATA LOCAL INFILE
'/tmp/dataset/football/shots.csv' INTO TABLE
shots FIELDS TERMINATED BY ',' LINES TERMINATED BY
'\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE
'/tmp/dataset/football/teamstats.csv' INTO TABLE
teamstats FIELDS TERMINATED BY ',' LINES TERMINATED BY
'\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE
'/tmp/dataset/football/games.csv' INTO TABLE
games FIELDS TERMINATED BY ',' LINES TERMINATED BY
'\n' IGNORE 1 ROWS;